language: python
# install:
#     - pip install Flask
# script:
#     - python app-test.py

services:
    - docker

before_install:
    - docker build . -t registry.cn-beijing.aliyuncs.com/zuoyeji/web-example

script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.cn-beijing.aliyuncs.com
    - docker push registry.cn-beijing.aliyuncs.com/zuoyeji/web-example:latest
